[package]
name = "eve"
version = "0.1.0"
authors = ["Chris Granger <ibdknox@gmail.com>"]

[profile.release]
debug = true

[dev-dependencies]
csv = "0.14"

[dependencies]
rand = "0.3.15"
fnv = "1.0.5"
time = "0.1.36"
libc = "*"
lazy_static = "0.2"

[dependencies.nom]
version = "^2.2"
features = ["verbose-errors"]
